name = "Arun's Blog"
license = "MIT"
licenselink = "https://github.com/thegeeklab/hugo-geekblog/blob/main/LICENSE"
description = "Hugo theme made for blogs"
homepage = "https://mkarundas.github.io"
demosite = "https://mkarundas.github.io"
tags = ["blog", "responsive", "simple"]
min_version = "0.93.0"

[author]
    name = "Arundas MK"
    homepage = "https://mkarundas.com/"
